In [30]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [31]:
dataset = pd.read_csv('50_Startups.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [32]:
print(X[:10, :])

[[165349.2 136897.8 471784.1 'New York']
 [162597.7 151377.59 443898.53 'California']
 [153441.51 101145.55 407934.54 'Florida']
 [144372.41 118671.85 383199.62 'New York']
 [142107.34 91391.77 366168.42 'Florida']
 [131876.9 99814.71 362861.36 'New York']
 [134615.46 147198.87 127716.82 'California']
 [130298.13 145530.06 323876.68 'Florida']
 [120542.52 148718.95 311613.29 'New York']
 [123334.88 108679.17 304981.62 'California']]


In [33]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(drop='first'), [3])], remainder='passthrough')
X = np.array(ct.fit_transform(X), dtype=np.float64)

In [34]:
print(X[:10,:])

[[0.00e+00 1.00e+00 1.65e+05 1.37e+05 4.72e+05]
 [0.00e+00 0.00e+00 1.63e+05 1.51e+05 4.44e+05]
 [1.00e+00 0.00e+00 1.53e+05 1.01e+05 4.08e+05]
 [0.00e+00 1.00e+00 1.44e+05 1.19e+05 3.83e+05]
 [1.00e+00 0.00e+00 1.42e+05 9.14e+04 3.66e+05]
 [0.00e+00 1.00e+00 1.32e+05 9.98e+04 3.63e+05]
 [0.00e+00 0.00e+00 1.35e+05 1.47e+05 1.28e+05]
 [1.00e+00 0.00e+00 1.30e+05 1.46e+05 3.24e+05]
 [0.00e+00 1.00e+00 1.21e+05 1.49e+05 3.12e+05]
 [0.00e+00 0.00e+00 1.23e+05 1.09e+05 3.05e+05]]


In [35]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [36]:
#X matrisinin soluna 1'den oluşan bir sütun ekle.Her örnek satırının başında bulunan 1 ilk theta parametresi ile çarpılarak biasin öğrenimini sağlar.
X_train_b = np.hstack((np.ones((X_train.shape[0], 1)), X_train))
X_test_b = np.hstack((np.ones((X_test.shape[0], 1)), X_test))

In [37]:
beta = np.linalg.inv(X_train_b.T.dot(X_train_b)).dot(X_train_b.T).dot(y_train)
print("Beta katsayıları:", beta)

Beta katsayıları: [ 4.26e+04 -9.59e+02  6.99e+02  7.73e-01  3.29e-02  3.66e-02]


In [38]:
y_pred = X_test_b @ beta

In [39]:
from sklearn.metrics import r2_score, mean_squared_error

np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(-1,1), y_test.reshape(-1,1)), axis=1))

mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print("R² skoru:", r2)
print("Ortalama Kare Hatası (MSE):", mse)
print("Karekök Ortalama Kare Hatası (RMSE):", rmse)

[[103015.2  103282.38]
 [132582.28 144259.4 ]
 [132447.74 146121.95]
 [ 71976.1   77798.83]
 [178537.48 191050.39]
 [116161.24 105008.31]
 [ 67851.69  81229.06]
 [ 98791.73  97483.56]
 [113969.44 110352.25]
 [167921.07 166187.94]]
R² skoru: 0.9347068473282446
Ortalama Kare Hatası (MSE): 83502864.03257468
Karekök Ortalama Kare Hatası (RMSE): 9137.990152794797
