<span style="color:blue; font-size:35px">ÖZDEĞERLER VE ÖZVEKTÖRLER</span>

<span style="color: red;font-size:15px">Kaynakça: </span><span style="font-size:15px">https://machinelearningmastery.com/introduction-to-eigendecomposition-eigenvalues-and-eigenvectors/</span>


<span style="font-size:15px">Matris ayrıştırmaları, bir matrisin kendini temsil eden daha küçük ve anlamlı parçalara ayrılabilmesini sağlayarakkarmaşık işlemleri basitleştirmek için kullanılan yararlı bir araçtır.<br>
Belki de en yaygın kullanılan matris ayrıştırma türü, bir matrisi özvektörlere (eigenvector) ve özdeğerlere (eigenvalue) ayıran öz ayrıştırmadır (eigendecomposition). Bu ayrıştırma, Temel Bileşenler Analizi (Principal Component Analysis - PCA) gibi makine öğrenmesinde kullanılan yöntemlerde de önemli bir rol oynar.</span>

<span style="color:red; font-size:20px">Matrisleri Öz Ayrıştırma İşlemi (Eigendecomposition of a Matrix)</span>

<span style="font-size:15px">Bir matrisin öz ayrıştırma işlemi bir kare matrisin özvektör ve özdeğerlere ayrışımı işlemidir.</span>

<span style="font-size:15px">Bir vektörün, bir matrisin özvektörü olabilmesi için A . v = lambda . v bu eşitliğin sağlanması şarttır.
<br>Bu eşitliğe özvektör eşitliği denir. Buradaki A parçalamak istediğimiz kare matrisi temsil eder, v A matrisinin özvektörü olur ve lambda özdeğeri temsil eder. <br>Ana matris özvektör ve özdeğerlerin çarpımı olarak tekrar üretilebilir. Bu üretim için A = Q . diag(V) . Q⁻¹ eşitliği kullanılır.<br>
Buradaki Q özvektörlerden oluşan matrisimizdir. Diag(V), özdeğerlerin köşegen üzerinde yer aldığı köşegen bir matristir. Q⁻¹ ise özvektörlerden oluşan matrisin tersidir. 
Q, özvektörlerden oluşan bir matristir; diag(V), özdeğerlerin köşegen üzerinde yer aldığı bir köşegen matristir (bazen büyük lambda harfiyle temsil edilir); ve Q⁻¹, özvektörlerden oluşan matrisin tersidir. 
    </span>

<span style="font-size:15px">Biraz da eigendecomposition'un makine öğrenmesindeki rolüne bakalım. Eigendecomposition Principal Component Analysis (PCA) yönteminde bir matrisin ana bileşenlerini hesaplamak için de kullanılabilir. PCA, makine öğrenmesinde verilerin boyutunu azaltmak için kullanılan bir tekniktir.<br>PCA, veriyi daha düşük boyutlu bir alana indirgemek için kullanılan güçlü bir tekniktir. Bu teknik, genellikle verinin çeşitliliğini en iyi şekilde temsil eden özellikleri (principal components) bulur ve bu özellikleri kullanarak veriyi daha az boyutla ifade eder. PCA, özdeğerler (eigenvalues) ve özvektörler (eigenvectors) kullanarak bu boyut indirgemeyi sağlar ve bu işlem Eigendecomposition olarak bilinir. Bu notebookun sonunda PCA algoritmasının çalışma mantığına detaylıca bakılacaktır.</span>

<span style="color:red; font-size:20px">Özdeğerler ve Özvektörler</span>

<span style="font-size:15px">Özvektörler birim vektörlerdir yani büyüklükleri 1 değerine eşit olur. Ayrıca sağ vektörler (right vectors) olarak da adlandırılırlar. Burada sağ vektör, vektörün sütun (column) formunda olduğunu belirtir.<br><br>
Özdeğerler, özvektörlere uygulanan çarpanlar (koefisiyentler) olarak düşünülebilir. Bu çarpanlar, özvektörlerin uzunluklarını (büyüklüklerini) değiştiren faktörlerdir.<br>
Eğer negatif bir özdeğer özvektörlerle işleme girerse bu işlem özvektörü ölçeklendirirken yön değiştirmesine neden olabilir.</span>

<span style="color:red; font-size:20px">Öz Ayrıştırma İşlemleri</span>

<span style="font-size:15px">Bir kare matrisin özdeğer-ayrışımı (eigendecomposition), verimli bir yinelemeli algoritmayla hesaplanabilir. Genellikle önce bir özdeğer bulunur, ardından bu özdeğere karşılık gelen özvektör elde edilir. NumPy'de bu işlem eig() fonksiyonu ile yapılabilir. Aşağıdaki örnekte, 3×3 boyutunda bir matris tanımlanır ve özdeğer-ayrışımı yapılarak özdeğerler ve özvektörler elde edilir.</span>

In [6]:
from numpy import array
from numpy.linalg import eig

A = array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("A = \n",A)

values, vectors = eig(A)
print("\nValues = ",values)
print("\nVectors = ",vectors)

A = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Values =  [ 1.61168440e+01 -1.11684397e+00 -3.38433605e-16]

Vectors =  [[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


<br><span style="color:red; font-size:20px">Özvektör Doğrulaması</span>

<span style="font-size:15px">Bir vektörün bir matrisin özvektörü olup olmadığını şöyle doğrularız:<br>
Aday özvektörü matrisle çarparız ve sonucu özdeğer ile aday özvektörün çarpımıyla karşılaştırırız. Değerler aynı çıkarsa aday özvektörümüz gerçek özvektörümüzdür.
</span>

In [10]:
A = array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

values, vectors = eig(A)

B = A.dot(vectors[:, 0])
print("B = ",B)
C = vectors[:, 0] * values[0]
print("\nC = ",C)

B =  [ -3.73863537  -8.46653421 -13.19443305]

C =  [ -3.73863537  -8.46653421 -13.19443305]


<br><span style="color:red; font-size:20px">Orijinal Matrisin Tekrar Elde Edilmesi</span>

<span style="font-size:15px">İzlenilen adımları tersten izleyerek bir matrisi onun özdeğerlerinden ve özvektörlerinden elde edebiliriz.<br>
Öncelikle özvektörler bir matrise dönüştürülmelidir, burada her bir vektör bir satır haline gelir. Özdeğerler ise köşegen (diyagonal) bir matrise yerleştirilmelidir. Bunun için NumPy'nin diag() fonksiyonu kullanılabilir.<br>
Sonrasında özvektör matrisinin tersini almamız gerekir, bunu da NumPy'nin inv() fonksiyonu ile gerçekleştirebiliriz. Son olarak, bu elemanların hepsi dot() fonksiyonu ile birbiriyle çarpılmalıdır.
</span>

In [12]:
from numpy import diag
from numpy import dot
from numpy.linalg import inv
A = array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\nA = ",A)

values, vectors = eig(A)

Q = vectors

R = inv(Q)

L = diag(values)

B = Q.dot(L).dot(R)
print("\nB =\n",B)


A =  [[1 2 3]
 [4 5 6]
 [7 8 9]]

B =
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


<br><span style="font-size:20px">Bu notebookda ayrıca PCA algoritmasını da değineceğiz.</span>

<br><span style="color: red;font-size:20px">Principal Component Analysis (Temel Bileşen Analizi)</span>

<span style="color: red;font-size:15px">Kaynakça: https://machinelearningmastery.com/calculate-principal-component-analysis-scratch-python/</span>
<br><span style="font-size:15px">Temel Bileşen Analizi ya da kısaca PCA (Principal Component Analysis), verinin boyutunu azaltmak için kullanılan bir yöntemdir. Bu yöntem, m sütunlu (özellikli) verinin, m veya daha az sütunlu bir alt uzaya yansıtıldığı bir projeksiyon yöntemi olarak düşünülebilir, bu sırada verinin özünü korunmasına dikkat edilir. PCA yöntemi, lineer cebirin araçları kullanılarak tanımlanabilir ve uygulanabilir.<br>PCA, n x m boyutlarında bir A veri matrisi üzerinde uygulanan bir işlemdir ve bunun sonucunda A'nın bir projeksiyonu olan B matrisi elde edilir. Şimdi bu işlemin adımlarının nasıl yapılacağı konusuna gelelim:
<br><br>İlk adım her sütunun ortalama değerini hesaplamaktır.<br>
İkinci adımda her sütundaki değerleri merkezlemek için tüm sütun değerlerini ortalama değerden çıkarırız.<br>
Sonraki adımda merkezlenmiş olan matrisimizin kovaryans matrisini hesaplarız.(Cov(A) = (1/(n-1))*A(Transpose)*A)<br>
Korelasyon, iki sütunun birlikte ne kadar ve hangi yönde (pozitif ya da negatif) değiştiğini gösteren normalize edilmiş bir ölçümdür.<br>
Kovaryans ise, korelasyonun daha genelleştirilmiş ve normalize edilmemiş hâlidir ve birden fazla sütun arasında kullanılır.<br>
Son olarak kovaryans matrisinin eigendecomposition değerini hesaplarız. Bu işlem, özdeğerler ve özvektörler listelerini elde etmemizi sağlar.<br><br>
Özvektörler, B'nin indirgenmiş alt uzayının yönlerini veya bileşenlerini temsil ederken, özdeğerler bu yönlerin büyüklüklerini temsil eder.<br>Özvektörler, özdeğerlerine göre azalan sırayla sıralanarak, A'nın yeni alt uzayının bileşenlerinin veya eksenlerinin bir sıralamasını sağlar.
<br>
Eğer tüm özdeğerler benzer bir değere sahipse, mevcut temsilin zaten makul derecede sıkıştırılmış veya yoğun olduğunu ve projeksiyonun pek fazla fayda sağlamayabileceğini anlarız. Eğer özdeğerler sıfıra yakınsa, bunlar B'nin atılabilecek bileşenlerini veya eksenlerini temsil eder.
<br>
Seçilen alt uzayı oluşturmak için toplamda m veya daha az bileşen seçilmelidir. İdeal olarak, en büyük k özdeğerine sahip olan k özvektörü, yani ana bileşenler seçilmelidir.
</span>

<br><span style="color: red;font-size:20px">PCA'yı Manuel Olarak Hesaplamak</span>

In [24]:
from numpy import mean
from numpy import cov
from numpy.linalg import eig
A = array([[1, 2], [3, 4], [5, 6]])
print("A = \n",A)

M = mean(A.T, axis=1)
print("\nMean =",M)

C = A - M
print("\nC = \n",C)

V = cov(C.T)
print("\nV =\n",V)

values, vectors = eig(V)
print("\nVectors = \n",vectors)
print("\nValues = \n",values)

P = vectors.T.dot(C.T)
print("\nP.T = \n",P.T)

A = 
 [[1 2]
 [3 4]
 [5 6]]

Mean = [3. 4.]

C = 
 [[-2. -2.]
 [ 0.  0.]
 [ 2.  2.]]

V =
 [[4. 4.]
 [4. 4.]]

Vectors = 
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]

Values = 
 [8. 0.]

P.T = 
 [[-2.82842712  0.        ]
 [ 0.          0.        ]
 [ 2.82842712  0.        ]]
