<span style="color:blue; font-size:25px">linalg.eig</span>

<span style="color:red; font-size:15px">Kaynakça: https://numpy.org/doc/2.1/reference/generated/numpy.linalg.eig.html</span>

<span style="font-size:15px">linalg.eig(a) fonksiyonu kare matrislerin özdeğerlerini ve sağ özvektörlerini hesaplar. Parametre olarak özdeğerleri ve özvektörleri hesaplanmak istenen matris girilir. Fonksiyon işlemlerinin sonucunda özdeğerleri ve özvektörleri döndürür. Özdeğerler belli bir değere yakınsamıyorsa da belli bir hata değeri döndürür.<br>
Bir w değerinin a matrisinin özdeğeri olabilmesi için a @ v = w * v eşitliğini sağlaması gerekir. Buradaki v de özvektördür.</span>


In [5]:
import numpy as np
from numpy import linalg as LA
eigenvalues, eigenvectors = LA.eig(np.diag((1, 2, 3)))
print("eigen values = ",eigenvalues)

print("\neigen vectors = \n",eigenvectors)

eigen values =  [1. 2. 3.]

eigen vectors = 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
def eig(a):#a, özdeğer ve özvektörleri bulunmak istenen kare (n x n) bir matristir.
    a, wrap = _makearray(a) #a, numpy dizisi haline getirilir.
    _assert_stacked_square(a) # a matrisinin kare olup olmadığının kontrolü
    _assert_finite(a) #Matrisin içinde sonsuz ya da tanımsız değerlerin varlığını kontrol eder.
    t, result_t = _commonType(a) # Veri tiplerini ayarlar.

    signature = 'D->DD' if isComplexType(t) else 'd->DD' # Karmaşık matrisler için D->DD imzası, gerçek matrisler için d->DD imzası kullanılır.

    with errstate(call=_raise_linalgerror_eigenvalues_nonconvergence, # burada hatalara bakılır, daha önce bahsettiğimiz yakınsama hatası gibi
                  invalid='call', over='ignore', divide='ignore',
                  under='ignore'):
        w, vt = _umath_linalg.eig(a, signature=signature) # NumPy kütüphanesinin C kütüphaneleri üzerinden özdeğer ve özvektör hesaplamasını yapan fonksiyon.

    if not isComplexType(t) and all(w.imag == 0.0): # Sonuçlar karmaşık mı?
        w = w.real
        vt = vt.real
        result_t = _realType(result_t)
    else:
        result_t = _complexType(result_t)

    vt = vt.astype(result_t, copy=False) # Özvektör tip dönüşümü
    return EigResult(w.astype(result_t, copy=False), wrap(vt))