<span style="color:blue; font-size:35px">MATRİS MANİPÜLASYONU</span>

<span style="font-size:20px">Matris manipülasyonu kavramı matrisler üzerinde yapılan matematik işlemlerini ifade eder. Bu işlemler toplama, çıkarma, skaler çarpım gibi işlemlerdir. Şimdi bu işlemleri kodlar üzerinde inceleyelim.</span>

<span style="color:red; font-size:15px">Kaynakça:</span> <span style="font-size:15px">https://machinelearningmastery.com/introduction-matrices-machine-learning/</span>

<br><span style="font-size:20px">Öncelikle çalışmamıza matrislerin ne olduğunu öğrenerek başlayalım.<br>
Matrisler bir veya daha fazla satır ve sütundan oluşan ve elemanları sayılar olan iki boyutlu dizilerdir.</span>

<br><span style="font-size:25px; color:red"> Bir Matrisin Tanımlanması</span>

In [13]:
from numpy import array
A = array([[1, 2, 3], [4, 5, 6]])
print(A)

[[1 2 3]
 [4 5 6]]


<br><span style="font-size:25px; color:red"> Matrislerde Toplama İşlemi</span>

In [14]:
A = array([[1, 2, 3], [4, 5, 6]])
print("\nA = \n",A)
B = array([[1, 2, 3], [4, 5, 6]])
print("\nB = \n",B)
C = A + B
print("\nC = \n",C)


A = 
 [[1 2 3]
 [4 5 6]]

B = 
 [[1 2 3]
 [4 5 6]]

C = 
 [[ 2  4  6]
 [ 8 10 12]]


<span style="font-size:17px">Buradaki dikkat edilmesi gereken nokta matrislerde çarpım(dot product) başlığına kadar olan kısmın hepsinde işleme girecek olan iki matrisin boyutlarının eşit olması gerekliliği(satır ve sütun sayısı bakımından) ve bu işlemlerin matrislerde aynı konumdaki elemanlar arasında (C[1,0] = A[1,0] + B[1,0]) yapıldığıdır.</span>

<br><span style="font-size:25px; color:red"> Matrislerde Çıkarma İşlemi</span>

In [15]:
A = array([[1, 2, 3], [4, 5, 6]])
print("\nA = \n",A)
B = array([[0.5, 0.5, 0.5], [0.5, 0.5, 0.5]])
print("\nB = \n",B)
C = A - B
print("\nC = \n",C)


A = 
 [[1 2 3]
 [4 5 6]]

B = 
 [[0.5 0.5 0.5]
 [0.5 0.5 0.5]]

C = 
 [[0.5 1.5 2.5]
 [3.5 4.5 5.5]]


<br><span style="font-size:25px; color:red"> Matrislerde Hadamard Çarpması</span>

In [16]:
A = array([[1, 2, 3], [4, 5, 6]])
print("\nA = \n",A)
B = array([[1, 2, 3], [4, 5, 6]])
print("\nB = \n",B)
C = A * B
print("\nC = \n",C)


A = 
 [[1 2 3]
 [4 5 6]]

B = 
 [[1 2 3]
 [4 5 6]]

C = 
 [[ 1  4  9]
 [16 25 36]]


<br><span style="font-size:25px; color:red"> Matrislerde Bölme İşlemi</span>

In [17]:
A = array([[14, 2, 3], [24, 19, 12]])
print("\nA = \n",A)
B = array([[7, 1, 3], [4, 5, 6]])
print("\nB = \n",B)
C = A / B
print("\nC = \n",C)


A = 
 [[14  2  3]
 [24 19 12]]

B = 
 [[7 1 3]
 [4 5 6]]

C = 
 [[2.  2.  1. ]
 [6.  3.8 2. ]]


<br><span style="font-size:25px; color:red"> Matrislerde Çarpma (Dot Product)</span>

<br><span style="font-size:15px;">Matris çarpımı için boyut uygunluğuna şu şekilde bakılır:
İlk matrisin(A) sütun sayısı(n) ile ikinci matrisin(B) satır sayısı(m) eşit olmalıdır. <br>
Eğer ilk matrisin(A) m satır ve n sütundan oluştuğunu ve ikinci matrisin(B) de n satır ve k sütundan oluştuğunu kabul edersek bu iki vektörün
çarpımı ile oluşan C matrisi m satır ve k sütuna sahip olur.
<br><br>Bu çarpımı uygulamak için A matrisinin her satırını B matrisinin her sütunu ile tek tek nokta çarpımına sokarız.</span>

![Matris çarpımını şekil üzerinde inceleyerek daha iyi anlayalım:](MatrixMultiplication.png)

In [18]:
A = array([[1, 2], [3, 4], [5, 6]])
print("\nA = \n",A)
B = array([[1, 2], [3, 4]])
print("\nB = \n",B)
C = A.dot(B)
print("\nC = \n",C)


A = 
 [[1 2]
 [3 4]
 [5 6]]

B = 
 [[1 2]
 [3 4]]

C = 
 [[ 7 10]
 [15 22]
 [23 34]]


<br><span style="font-size:25px; color:red"> Matris-Skaler Çarpımı</span>

<span style="font-size:15px;">C[0,0] = A[0,0] * b<br>C[1,0] = A[1,0] * b<br>C[2,0] = A[2,0] * b ....</span>

In [19]:
A = array([[1, 2], [3, 4], [5, 6]])
print("\nA = \n",A)
b = 0.5
print("\nb = ",b)
C = A * b
print("\nC = \n",C)


A = 
 [[1 2]
 [3 4]
 [5 6]]

b =  0.5

C = 
 [[0.5 1. ]
 [1.5 2. ]
 [2.5 3. ]]
